### ISSUE TITLE
feat: crafting rotation simulator

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#331]
I'll use this issue as a task tracker so I can track progress and anybody can too 😃 .

# TODO

 - [x] Repair actions (Master's Mend I & II)
 - [x] Rumination
 - [x] Innovative Touch
 - [x] Specialties
 - [x] Ideal mode (all success everywhere, for UI).
 - [x] Reliability % calculation
 - [x] First UI
 - [x] Food implementation
 - [x] HQ ingredients implementation
 - [x] Drag&Drop for reordering
 - [x] Full custom mode implementation (custom recipe numbers)
 - [x] Skill tooltip on hover
 - [x] Synth state implementation (good, excellent, poor)
 - [x] Synth reliability display
 - [x] Whistle while you work implementation
 - [x] Element actions
 - [x] More tests
 - [x] Lokyst-like websites import/export
 - [x] Rotation saved inside database
 - [x] Macro generation
 - [x] Persist food with rotation
