### ISSUE TITLE
[5.0] List details page rework

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#576]
As of 5.0 update, list details page has to be heavily reworked, including a lot of things, first of all we should list all the features available on list-details page:

- [x] Regenerate list (recreate it and re-apply progression)
- [x] Clone list
- [x] Edit list name
- [x] Create all alarms for the list at once
- [x] Layout system (rework the configuration modal)
- [x] Tags
  - [x] New `Scripts` tag
- [x] Good perfs even with big lists (#557)
- [x] Modifications history
- [x] Reset list (set progression to 0)
- [x] Inventory view
- [x] Manage permissions for the list
- [x] Filters for view, persisted on the user
  - *Filter by job/level* (TBD)
  - *Adapt filters to current character (to see what you can do)* (TBD)
  - [x] Hide completed rows (done === amount)
  - [x] Hide used rows
- [x] Enable/disable crystals tracking
 - [x] Add/remove list in favorites
 - [x] Pricing mode

Features for panels:

 - ~Optimized route, per map (one tab per map)~ (wont do because too complex and kinda niche)
 - [x] Button to copy panel as text output for chats
 - [x] Button to see total price for a given panel (if items with vendor informations > 1)
 - [x] Optimized navigation route if it has some value (items with coordinates > 2)
 - [x] Collapse when all done (layout option?)

Features for item rows:

- [x] Show item icon
- [x] Show item name, localized
- [x] Button to create alarms for this item (includes reductions)
- [x] Copy item name on name click
- [x] Button to copy `/isearch <item name>` macro
- [x] Better remaining amounts display (amount of crafts remaining for when yield > 1)
- [x] Informations about how to get the item
  - [x] Rework trades dialog box (#559)
  - [x] Rework all informations dialog boxes (see extractors)
- [x] Ability to check a row to say "I'm on it"
- [x] Ability to see row's relationships (required by, requires)
- [x] Show masterbooks if there's some
  - [x] If the masterbook isn't in the profile, show a warning and allow for an easy "I have this book" interaction (#555)
- [x] Ability to comment a row
- [x] Easy add/remove operations (currently made by the calculator icon)
- [x] Button to assign to a team member if the list is linked to a team and you're the leader
- [x] Link to the simulator with rotations choice
- [x] Ability to mark an item as HQ even if it's not required for final craft (if it's required for a hard craft for instance)
- [x] Edit item amounts from the list details view
