### ISSUE TITLE
feat:Gathering/Fishing log tracker

### ISSUE THREAD

**Issue by MDlumia** [Supamiu/ffxiv-teamcraft#732]
**Is your feature request related to a problem? Please describe.**
Yes, i have seen the crafting log tracker and i noticed that it would be super nice to have a Gathering log tracker for Miner BTN and maybe Fisher. 

**Describe the solution you'd like**
Idealy it would be the same as the crafting log tracker but tailored to Gathering classes and logs. 

**Describe alternatives you've considered**
there is none to be honest. well their is a half baked approach for the FSH but its tied to cat got hungry and no way to keep your progress if you have a new system and forget to back up the client programs settings.  i have a feeling you could do better with TC.

**Comment by Supamiu** [comment]
Related to #653 for FSH

**Comment by MDlumia** [comment]
would it be possible to have what bait and such added to the  log?

**Comment by Supamiu** [comment]
Yes, it's the goal :)

**Comment by ayyaruq** [comment]
Specifically for fishing (and noted/requested by @rexatlanti), the following metadata is worth having:
- [ ] weather
- [ ] time
- [ ] bait
- [ ] tug strength, maybe duration?
- [ ] hook type
- [ ] mooch chains (maybe the same way we show vendor trades in sequence?)
- [ ] fish eyes buff status (fish eyes works on only one fish at a time, but which fish is random, they can be identified by how long the buff lasts as it's different per fish)
- [ ] status gained from fishing other stuff in the area
- [ ] other buffs/skill requirements that I forgot like the one that looks like 3 hooks on the line

**Comment by Supamiu** [comment]
What are "tug strength" and "status gained from fishing other stuff in the area"?

If the first one refers to either the noise made when the fish is hooked or the duration before it hooks, I wont display that because it's not an information that is worth it in my opinion.

Regarding the status gained, I have no idea what this means.

**Comment by ayyaruq** [comment]
Some of this may be better on the fish page, but being able to see and action in the log directly would be super nice.

Tug strength tells you how much the rod bends. To save time under buffs for big fishing, many people will intentionally not hook the fish unless it’s correct strength, since losing a fish is faster than the catch animation. Many fishing buffs only last one minute, so it makes a noticeable difference. Duration is useful for a similar reason, you can profile what fish it’s goinf to be.

Status is usually Intuition. When you catch a certain fish enough times, you get flying text to indicate the buff will be available soon. After more catches you gain a buff which unlocks extra fish in the area, or an unspoiled node like spearfishing point.

Regarding Fish Eyes, you marked it off but do you support the different varieties of it and pinning them to specific fish?

**Comment by Supamiu** [comment]
I don't know different varieties of fishing eyes but it's on the fishes that need it.

Also, didn't know about intuition, we have predators system, it can tell you which fishes you need to fetch before you can get a given one tho. A good example is sea butterfly.

**Comment by ayyaruq** [comment]
Cool, already implemented is the best kind of implemented. Probably need manually collated data for Fish Eyes then.

**Comment by rexatlanti** [comment]
Fish Eyes Fish (best mechanic)

HEAVENSWARD
```
bloodchaser : ?m
mountain kraken : 3m
aetherochemical compound #666 : ?m
warballoon : ?m
thousand fin : ?m
crystal pigeon : ?m
ceti : 2?m
merciless : 2.5m
hraesvelgr's tear : 2.5m
black magefish : 2?m
dimorphodon : ?m
goblin bass : ?m
inkfish : 6m

(Anyx Old)
riddle : 5m
magma louse : 5m

(Clearpool)
capelin : 3?m
bishopfish : 3?m
priestfish : 4?m

(The Flagship)
functional proto-hropken : 2m
barreleye : 3m

(Halo)
fossiltongue : 3m
lavalord : 4m
the lord of lords : 5m
```


STORMBLOOD
```
hak bitterling : ?m
tawny wench shark : ?m
silken koi : 4m
wraithfish : ?m

(Plum Spring)
silken koi: 4m
hagoromo koi: 4m

(Loch Seld)
sculptor : 4m
diamond-eye: 4m

(Onokoro)
swordfish : 4m
blackfin snake eel: 3m
```

**Comment by Supamiu** [comment]
Okay, I'll just convert that to JSON format using fish ids and will get this supported for the feature 👍

**Comment by MDlumia** [comment]
also tug str and hook type are similar, there are 3  kinds of tugs, small Medium and large.  and they they use 2 different hooksets under  Patience/ Patience II. it is Small uses Precision hookset  and med and large use Powerful Hookset.  its also helpful on telling what fish one might be getting as well. but there is the explanation that might been asked for.
